### ISSUE TITLE
Add support to fraction numbers

### ISSUE THREAD

**Issue by chrspx** [Igor-Palaguta/LiteralsExtension#1]
the extension doesnt works when I pass a fraction to UIColor constructor . For example: 

UIColor(red: 14/255, green: 93/255, blue: 149/255, alpha: 1)

14/255, 93/255, 149/255 are ignored by the extension, so we have to calculate each fraction before to make the extension works. It would be great if this could be done automatically by the extension.

**Comment by Igor-Palaguta** [comment]
Hello @chrspx 

Thanks for feedback

Please check https://github.com/Igor-Palaguta/LiteralsExtension/commit/75c0b34f52bc162368e480c95fbd9f492e0737c9

**Comment by Igor-Palaguta** [comment]
@chrspx did it work for you? can I close the issue?

**Comment by chrspx** [comment]
ty very much :)
